from Bio import pairwise2
from Bio.pairwise2 import format_alignment

normal_p53 = (
    "SQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPRMPEAAPPVAPAPAAPTPAAPAPAPSWPL"
)

muted_p53 = (
    "SQETFSDLWKLLPENNVLSPLPSQAMDDLMLSPDDIEQWFTEDPGPDEAPRMPEAAPPVAPHAPTPAAPAPAPSWPL"
)



